import { NextRequest, NextResponse } from "next/server";
import {
  processContent,
  classifyOnly,
  buildViralSignalsOnly,
} from "@/server/lib/processor";
import { createClient } from "@supabase/supabase-js";
import type { ClientPersona, ViralSignals } from "@/types/content";

function getServiceClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("Supabase env vars not set");
  return createClient(url, key);
}

function validateWebhookSecret(req: NextRequest): boolean {
  const secret = req.headers.get("x-telegram-bot-api-secret-token");
  return secret === process.env.TELEGRAM_WEBHOOK_SECRET;
}

// ─── ScoutBot structured payload ─────────────────────────────────────────────
// ScoutBot sends a JSON string as the Telegram message text.
// All fields from `feed_copy_en` onwards are optional — partial payloads
// are valid; missing fields will be generated by the AI processor.
//
// Expected shape (sent as JSON-stringified Telegram message text):
// {
//   "title": "...",
//   "source_url": "https://...",      (optional)
//   "raw_excerpt": "...",
//   "feed_copy_en": "...",            (if ScoutBot already generated)
//   "stories_script_he": "...",       (if ScoutBot already generated)
//   "client_persona": "dreamer_founder",  (optional)
//   "tags": ["AI", "design"],         (optional)
//   "engagement": {                   (optional — from Apify)
//     "shares": 1200,
//     "comments": 45,
//     "saves": 320,
//     "trend_tags": ["#AIDesign"]
//   }
// }

interface ScoutBotPayload {
  title: string;
  source_url?: string;
  raw_excerpt?: string;
  feed_copy_en?: string;
  stories_script_he?: string;
  client_persona?: ClientPersona;
  tags?: string[];
  engagement?: {
    shares?: number;
    comments?: number;
    saves?: number;
    trend_tags?: string[];
  };
}

interface TelegramUpdate {
  message?: {
    text?: string;
    chat?: { id: number };
  };
}

// ─── Processing decision ──────────────────────────────────────────────────────

type ProcessingMode =
  | "skip_all"       // ScoutBot sent copy + persona + tags — save directly
  | "classify_only"  // ScoutBot sent copy but no persona/tags — one Claude call
  | "full";          // Raw text — three Claude calls

function detectMode(payload: ScoutBotPayload): ProcessingMode {
  const hasCopy =
    typeof payload.feed_copy_en === "string" && payload.feed_copy_en.trim().length > 0 &&
    typeof payload.stories_script_he === "string" && payload.stories_script_he.trim().length > 0;

  const hasClassification =
    typeof payload.client_persona === "string" &&
    Array.isArray(payload.tags) && payload.tags.length > 0;

  if (hasCopy && hasClassification) return "skip_all";
  if (hasCopy) return "classify_only";
  return "full";
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  if (!validateWebhookSecret(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: TelegramUpdate;
  try {
    body = (await req.json()) as TelegramUpdate;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const text = body.message?.text?.trim();
  if (!text) {
    return NextResponse.json({ ok: true, skipped: true });
  }

  // Try to parse as a ScoutBot structured JSON payload first.
  // Fall back to plain-text parsing if it isn't valid JSON.
  let payload: ScoutBotPayload;
  try {
    const parsed = JSON.parse(text) as unknown;
    if (
      parsed &&
      typeof parsed === "object" &&
      "title" in parsed &&
      typeof (parsed as ScoutBotPayload).title === "string"
    ) {
      payload = parsed as ScoutBotPayload;
    } else {
      throw new Error("Not a ScoutBot payload");
    }
  } catch {
    // Plain Telegram text — extract title + excerpt from message lines
    const urlMatch = text.match(/https?:\/\/[^\s]+/);
    const lines = text.split("\n");
    payload = {
      title: lines[0]?.slice(0, 200) ?? "Untitled",
      source_url: urlMatch?.[0],
      raw_excerpt: lines.slice(1).join("\n").trim() || text,
    };
  }

  const { title, source_url, raw_excerpt } = payload;
  const rawExcerpt = raw_excerpt ?? title;

  const engagementData = payload.engagement
    ? {
        shares: payload.engagement.shares,
        comments: payload.engagement.comments,
        saves: payload.engagement.saves,
        trendTags: payload.engagement.trend_tags,
      }
    : undefined;

  const mode = detectMode(payload);

  try {
    // ── Resolve fields based on processing mode ───────────────────────────────
    let feedCopyEn: string;
    let storiesScriptHe: string;
    let clientPersona: ClientPersona;
    let tags: string[];
    let visualDirection: string;
    let viralSignals: ViralSignals;
    let aiCallsUsed: number;

    if (mode === "skip_all") {
      // ScoutBot did all the work — zero Claude calls
      feedCopyEn = payload.feed_copy_en!;
      storiesScriptHe = payload.stories_script_he!;
      clientPersona = payload.client_persona!;
      tags = payload.tags!;
      visualDirection = "";
      viralSignals = buildViralSignalsOnly(engagementData, 80);
      aiCallsUsed = 0;
    } else if (mode === "classify_only") {
      // ScoutBot generated copy but not classification — one Claude call
      const classification = await classifyOnly({ title, rawExcerpt, sourceUrl: source_url, engagementData });
      feedCopyEn = payload.feed_copy_en!;
      storiesScriptHe = payload.stories_script_he!;
      clientPersona = classification.clientPersona;
      tags = classification.tags;
      visualDirection = classification.visualDirection;
      viralSignals = classification.viralSignals;
      aiCallsUsed = 1;
    } else {
      // Raw text — full three-call processing
      const processed = await processContent({ title, rawExcerpt, sourceUrl: source_url, engagementData });
      feedCopyEn = processed.feedCopyEn;
      storiesScriptHe = processed.storiesScriptHe;
      clientPersona = processed.clientPersona;
      tags = processed.tags;
      visualDirection = processed.visualDirection;
      viralSignals = processed.viralSignals;
      aiCallsUsed = 3;
    }

    // ── Save to DB ────────────────────────────────────────────────────────────
    const supabase = getServiceClient();

    const { data, error } = await supabase
      .from("content_pieces")
      .insert({
        title,
        source_url: source_url ?? null,
        raw_excerpt: rawExcerpt,
        feed_copy_en: feedCopyEn,
        stories_script_he: storiesScriptHe,
        visual_direction: visualDirection || null,
        client_persona: clientPersona,
        status: "inbox",
        source: "telegram",
        tags,
        viral_signals: viralSignals,
      })
      .select()
      .single();

    if (error) throw error;

    // ── Audit log ─────────────────────────────────────────────────────────────
    await supabase.from("pipeline_logs").insert([
      {
        content_id: data.id,
        event: "ingested",
        payload: { source: "telegram", mode, ai_calls_used: aiCallsUsed },
      },
      ...(aiCallsUsed > 0
        ? [
            {
              content_id: data.id,
              event: "ai_processed" as const,
              payload: {
                model: "claude-sonnet-4-6",
                calls: aiCallsUsed,
                mode,
              },
            },
          ]
        : []),
    ]);

    return NextResponse.json({ ok: true, id: data.id, mode, aiCallsUsed });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("[ingest/telegram]", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
